name: Deploy to Remote Server

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to Remote Server
      env:
        REMOTE_USER: Nikinikk
        REMOTE_HOST: 20.251.140.210
        REMOTE_PATH: /var/www/html/nginxTest
      run: |
        ssh -o StrictHostKeyChecking=no $REMOTE_USER@$REMOTE_HOST << 'EOF'
          cd $REMOTE_PATH
          ls -al
          #sudo git pull origin main
        EOF
